config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
    resources :users, only: [:index, :show] do
    get :likes, on: :member
  end

  resources :articles do
  	 resource :likes, only: [:create, :destroy]
  end
  resources :comments, only:[:create]

  get 'search/index' => 'articles#index', as: :search
  root 'articles#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
	has_many :likes, dependent: :destroy

	validates :image, presence: { message: 'は、必須項目です。' }
	validates :title, presence: { message: 'は、必須項目です。' }
	validates :body, presence: { message: 'は、必須項目です。' }
	validates :country, presence: { message: 'は、必須項目です。' }
	validates :region, presence: { message: 'は、必須項目です。' }

	scope :get_title, -> (title){
		where("title like ?", "%#{title}%").order(id: "DESC")
	}
	scope :get_country, -> (country){
		where("title like ?", "%#{country}%").order(id: "DESC")
	}
	scope :get_price, -> (price){
		where("price <= ?", "#{price}").order(id: "DESC")
	}

  	def like_user?(user_id)
   		likes.where(user_id: user_id).present?
  	end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
    belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    articles_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:destroy, :show, :edit, :update]
    before_action :authenticate_user!, only:[:new, :edit]

	def top
	end

	def index
		@articles = Article.all.order("title DESC")
		@articles = Article.page(params[:page]).per(12)
		if params[:title].present?
      		@articles = @articles.get_title params[:title]
    	end
    	if params[:country].present?
      		@articles = @articles.get_country params[:country]
    	end
    	if params[:price].present?
      		@articles = @articles.get_price params[:price]
    	end
		@new_articles = Article.limit(4).order("updated_at DESC")
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(set_params)
		@article.user_id = current_user.id
		if  
			@article.save then
			redirect_to articles_path
		else
			re = ''
			@article.errors.messages.each do |key, vals|
				vals.each do |val|
					re += '<span style="color:red">' + key.to_s + '</span>' + val
				end
			end
			@msg = re.html_safe
			render 'articles/new'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end
    
    def show
    	user_id = @article.user_id
    	@user = User.find(user_id)
    end

    def edit
    	
    end

    def update
    	if  
			@article.update(set_params) then
			redirect_to articles_path
		else
			re = ''
			@article.errors.messages.each do |key, vals|
				vals.each do |val|
					re += '<span style="color:red">' + key.to_s + '</span>' + val
				end
			end
			@msg = re.html_safe
			render 'articles/edit'
		end
    end

	private
	def set_article
		@article = Article.find(params[:id])
		
	end
	def set_params
		params.require(:article).permit(:body, :image, :price, :from_date, :to_date, :country, :region, :safety_info, :travel_item, :user_id, :title)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		# いいねを押されたarticleを探してくる
		@article = Article.find(params[:article_id])
		# いいねされたarticle.idといいねを押した（ログインしているユーザー）user.idそれぞれカラムにセットしてテーブルへ保存
		Like.create(user_id: current_user.id, article_id: @article.id)
		# @likes = Like.where(article_id: params[:article_id])
		# -----------------------
		# いいねをカウントしたいのであれば
		# @article.likes.count  or  @article.likes.size
		# で計測可能
		# ビューで表示するときは
		# <%= @article.likes.count %>
		# でおけ
		# ------------------------
		# @articles = Article.all
  	end

	def destroy
		@article = Article.find(params[:article_id])
	    like = Like.find_by(user_id: current_user.id, article_id: @article.id)
	    like.destroy
	    # 上に同じく不要なコード
	    # @likes = Like.where(article_id: params[:article_id])
	    # @articles = Article.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id])
      @artcles = @user.articles
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/syntax_helper.rb
module SyntaxHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer:language)
      end
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="form-wrapper">
  <div class="create-title">
    <h1>Create Story</h1> 
  </div>

  <hr>

  <%= form_for @article do |f| %>
  　　<%= @msg %>

  <section class="main-article-form">
    <div class="form-infoarea clearfix" style="padding-bottom: 50px;">
      <div class="info-left col-sm-5 col-xs-12">
      　 <p>
          <%= f.label :title %> 
          <%= f.text_field :title, placeholder: "Title" %>
        </p>
        <p>
      		<%= f.label :MainImage, "MainImage(一覧に表示されます)" %>
      		<%= f.file_field :image %>
      	</p>
      	<p><%= f.label :from_date, 'Start' %><br>
           <%= raw sprintf(
            f.datetime_select(
               :from_date,# プロパティ名
              {
                start_year:     Time.zone.now.prev_year.year,# 選択可能な開始年
                end_year:       Time.zone.now.next_year.year,# 選択可能な終了年
                default:        Time.zone.now,# デフォルトの年
                #use_two_digit_numbers: true,# 月日を2桁の値で表示
                #date_separator: '%s',# 年, 月
                #datetime_separator: '%s',# 日
                #time_separator: '%s'# 時
              },# オプション
              { class: 'date-select' }# htmlオプションを指定する場合は別で指定
            ),
            '年 ', '月 ', '日 ', '時') + '分'# 分 は最後につけ加えられる
           %>
        	</p>
          <p>
            <%= f.label :price %>
            ￥<%= f.text_field :price, placeholder: "10000" %>
          </p>
        </div>
        <div class="info-right col-sm-7 col-xs-12">
      		<p>
      			<%= f.label :country %>
      			<%= f.text_field :country, placeholder: "日本" %>
      		</p>
      		<p>
      			<%= f.label :region %>
      			<%= f.text_field :region, placeholder: "東京" %>
      		</p>
      		<p>
      			<%= f.label :travel_item %>
      			<%= f.text_field :travel_item, placeholder: "地図、etc" %>
      		</p>
      		<p>
      			<%= f.label :safety_info, "これから行く人へ一言" %>
      			<%= f.text_field :safety_info, placeholder: "行ってらっしゃい！！" %>
      		</p>
        </div>
      </div>

      <hr>

      <div class="form-bodyarea">

        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#editor">エディタ</a></li>
          <li><a data-toggle="tab" href="#mkdown">マークダウン</a></li>
        </ul>

        <div class="tab-content">
          <div id="editor" class="tab-pane fade in active">
            <p>
              <%= f.cktext_area :body, class: "editor" %>
            </p>

            <hr>

            <p class="article-submit">
              <%= f.submit "Submit", class: "btn btn-default" %>
            </p>
          </div>
          <div id="mkdown" class="tab-pane fade">
            <p>
              <%= f.text_area :body, as: :pagedown, input_html: { preview: true, rows: 20 }, class: "mk-editor" %>
            </p>

            <hr>

            <p class="article-submit">
              <%= f.submit "Submit", class: "btn btn-default" %>
            </p>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/articles/_header.html.erb
<header id="header" class="main-head">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "RECERDO", root_path, class: "navbar-brand" %>
        </div>
            <ul class="nav navbar-nav">
              <li class=""><%= link_to "Stories", articles_path %></li>
          <% if user_signed_in? %>
                <li class=""><%= link_to "Create Story", new_article_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                  <li>
                    <%= link_to user_path(current_user.id) do %>
                      <span class="glyphicon glyphicon-user">　My Stories</span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <span class="glyphicon glyphicon-log-out">　Sign Out</span>
                    <% end %>
                  </li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Travels", articles_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in">　Sign In</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-pencil">　Sign Up</span>
                <% end %>
              </li>
            </ul>

          <% end %>
        </ul>
      </div>
    </nav>
</header>

app/views/articles/edit.html.erb
<%= render 'header' %>

	
  	<div class="render_form">
  		<%= render'form' %>	
  	</div>

app/views/articles/index.html.erb
<%= render 'header' %>

<div class="ind-main-img">
	<%= image_tag "photo.jpg", class: "ind-main-img" %>
</div>

<!-- 一覧セクション -->
<hr>
<section class="index-sec clearfix">
	<div class="index-wrapper1 container">
		<div class="row">
		<% @articles.each do |article| %>
			<div class="col-md-3 col-sm-6 col-xs-12 ind-box">
				<p class="index-img"><%= image_tag article.image, class: "i-img" %></p>
				<div class="index-cont">
					<h3 class="ind-title"><%= article.title %></h3>
					<p class="ind-title">-　<%= article.region %></p>
					<p class="ind-title">-　￥<%= article.price %></p>
					<p class="like">
						<i class="fa fa-heart"></i>
						<%= article.likes.count %>
					</p>
					<%= link_to article_path(article) do %>
					<span class="btn btn-default">Read More</span>
					<% end %>
				</div>
			</div>
		<% end %>
		</div>
	</div>
	<div class="index-wrapper2 container">
		<div class="search">
			<%= form_tag(search_path, method: :get) do %>
	      	<div class="modal-body">
	        	<p class="search-form">
	          タイトル検索<br>
	          <%= text_field_tag :title %>
	        	</p>
	      	</div>
      		<div class="modal-body">
        		<p class="search-form">
          			国で検索<br>
          		<%= text_field_tag :country %>
        		</p>
      		</div>
      		<div class="modal-body">
	        	<p class="search-form">
		          予算で検索<br>
		          <%= text_field_tag :price %>
	        	</p>
      		</div>
	        <p class="search-btn">
	          	<%= submit_tag '検索', class: "btn btn-default" %>
	        	</p>
      		<% end %>
		</div>
		<div class="arrow_box">
				New!!
		</div>
		<% @new_articles.each do |article| %>
			<div class="new-inde row clearfix">
				<p class="index-img2 col-md-5 col-sm-12"><%= image_tag article.image, class: "n-img" %></p>
				<div class="index-cont2 col-md-7 col-sm-12">
					<h4 class="ind-title"><%= article.title %>
					</h4>
					<p class="ind-title2">-　<%= article.region %></p>
					<p class="ind-title2">-　￥<%= article.price %></p>
					<%= link_to article_path(article) do %>
					<span class="btn-md btn-default">Read More</span>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</section>
<%= paginate @articles %>

  

app/views/articles/new.html.erb
<%= render 'header' %>
<div class="form-sec">
	<div class="render_form"><%= render'form' %></div>
</div>

app/views/articles/show.html.erb
 <%= render 'header' %>

 <hr>
<div class="show-wrapper container">
	<section class="show_article row">
		<div class="show_side-article col-sm-3">
			<div class="show_side-username">
				<p class="show_username"><%= link_to @user.name, user_path(@user.id) %>
				</p>
			</div>
			<div class="arrow_box">
				Info!
			</div>
			<div class="show_side-info" style="margin-top: 20px;">
				<span class="infotitle">場所</span>
				<p><%= @article.country %>,<%= @article.region %></p>
			</div>
			<div class="show_side-info">
				<span class="infotitle">予算</span>
				<p><%= @article.price %></p>
			</div>
			<div class="show_side-info">
				<span class="infotitle">日にち</span>
				<p><%= @article.from_date %></p>
			</div>
			<div class="show_side-info">
				<span class="infotitle">重要な持ち物</span>
				<p><%= @article.travel_item %></p>
			</div>
			<div class="show_side-info">
				<span class="infotitle">これから行く人へ一言</span>
				<p><%= @article.safety_info %></p>
			</div>
				<%= render 'likes/like', article: @article %>　
				<% if @article.user_id == current_user.id %>
					<%= link_to edit_article_path(@article.id) do %>
						<span class="glyphicon glyphicon-pencil" style="font-size: 25px;"></span>
					<% end %>　
					<%= link_to article_path(@article.id), method: :delete, "data-confirm" => "Are you sure?" do %>
						<span class="glyphicon glyphicon-trash" style="font-size: 25px;"></span>
					<% end %>
				<% end %>
				<div class="arrow_box">
				Share!
				</div>
			<h3 class="show_share-btn">
				<%= social_share_button_tag(@article.id) %>
			</h3>
		</div>
		<div class="show_body-article col-sm-9">
			<div class="show_body">
				<h1 class="show_body-title"><%= @article.title %>
				</h1>
				<span class="cre-time"><%= @article.updated_at %>
				</span>
				<div class="show_body-body">
					<p class="body-body">
					<%= markdown(@article.body).html_safe %>
					</p>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/articles/top.html.erb
 <div class="articles-top">
 	<div class="container-fulid">
 		<div class="row">
  	  		<div class="parallax-window-top" data-parallax="scroll" data-image-src="<%= asset_path "london.jpg" %>">
     				<div class="top-title col-lg-6">recuerdo</div>
     			</div>
    		</div>
			<section class="top-sec">
				<div class="page-top-scroll">
					<p id="page-top"><a href="#wrap">See more</a></p>
						<div id="content">
							<i id="rect" class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
						</div>
					</div>
			</section>
			<div class="parallax-window" data-parallax="scroll" data-image-src="<%= asset_path "prague.jpg" %>"></div>
				<div class="top-sec low">
					<div class="top-sec-sentences-btn col-md-4">
						<div class="top-sec-sentences">	
							<a href="#xxx">Souvenir story</a>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.</p>
						</div>
						<div class="btn05">
							<%= link_to articles_path do %>
    							<span class="front">Travels</span>
    							<span class="back">Travels</span>
    						<% end %>
						</div>
					</div>
					<div class="top-img col-md-4">
						<img src="<%= asset_path "port05.jpg" %>" class='img-thumbnail' alt="Cinque Terre" width="360" height="250">
					</div>
					<div class="top-img col-md-4">
						<img src="<%= asset_path "port06.jpg" %>" class='img-thumbnail' alt="Cinque Terre" width="360" height="250">
					</div>
				</div>
			<div class="parallax-window" data-parallax="scroll" data-image-src="<%= asset_path "krakow.jpg" %>"></div>
					<div class="top-sec row">
						<div class="second-top-img1 col-md-4">
							<img src="<%= asset_path "directory.jpg" %>" class='img-thumbnail' alt="Cinque Terre" width="350" height="150" style="margin-left: 40px;">
						</div>
						<div class="second-top-img2 col-md-4">
							<img src="<%= asset_path "luggage.jpg" %>" class='img-thumbnail' alt="Cinque Terre" width="360" height="250">
						</div>
						<div class="top-sec-sentences-btn col-md-4">
							<div class="second">
								<img class= "logo-img" src="<%= asset_path "logo.png" %>">	
								<a href="#xxx">RECUERDO</a>
								<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever.Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
							</div>
						</div>
					</div>
				<div class="parallax-window" data-parallax="scroll" data-image-src="<%= asset_path "night.jpg" %>"></div>
				<div class="top-sec third row">
					
						<% if user_signed_in? %>
              				<div class="col-md-4 logout-user"><%= link_to "Create Travel", new_article_path, class: "link-button" %></div>
                			<div class="col-md-4 logout-user"><%= link_to "My Page", user_path(current_user.id), class: "link-button" %></div>
               				<div class="col-md-4 logout-user"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "link-button"%></div>
         				 <% else %>
              				<div class="col-md-6 login-user"><%= link_to "Sign In", new_user_session_path, class: "link-button" %></div>
                			<div class="col-md-6 login-user"><%= link_to "Sign Up", new_user_registration_path, class: "link-button" %></div>
        			 	 <% end %>
		  		</div>
		<div class="parallax-window" data-parallax="scroll" data-image-src="<%= asset_path "clouds.jpg" %>"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTravelApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
  <!-- ログインしているユーザーがいいねしてるかどうか -->
  <% if article.like_user?(current_user.id) %>
    <%= link_to article_likes_path(article.id), method: :delete, id: "like-button", remote: true do %>
      <i class="fa fa-heart fa-2x"></i>
    <% end %>
  <% else %>
    <%= link_to article_likes_path(article.id), method: :post, id: "like-button", remote: true do %>
    <i class="fa fa-heart-o fa-2x"></i>
    <% end %>
  <% end %>

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render 'likes/like', article: @article ) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render 'likes/like', article: @article ) %>");

app/views/users/show.html.erb
<%= render 'articles/header' %>
<div class="container">
	<div class="row">
		<div class="my-info col-md-3">
		 	<h3 class="panel-heading">NAME</h3>
			<h4 class="well"><%= @user.name %></h4>
		 </div>
		 <div class="col-md-9">
			<ul class="nav nav-tabs">
	  			<li class="users_show_text active"><a data-toggle="tab" href="#tab1">投稿した記事</a></li>
		  		<li class="users_show_text"><a data-toggle="tab" href="#tab2">いいねした記事</a></li>
   			</ul>
  	 		<div class="tab-content" style="height: 800px;">
  	 			<div class="tab-pane fade in active" id="tab1">
	  	 			<div class="row">
	 					<% @artcles.each do |article| %>
	 						<div class="col-sm-4">
	   					 		<p><%= link_to article.title ,article_path(article.id) %></p>
	   			 				<div><%= image_tag article.image.url, class: "users-like-img" %></div>
	  		  					<p><i class="fa fa-heart"></i><%= article.likes.count %></p>
	  		  				</div>
	  		  			<% end %>
	 				</div>
 				</div>
 				<div class="tab-pane fade" id="tab2">
 					<div class="no-article row">
   						<% if @user.likes.empty? %>
   							<div class="list-group-item col-md-12">
    							まだお気に入りした記事はありません。
	  						</div>
	  					<% else %>
		  					<% @user.likes.map { |f| f.article }.each do |article| %>
	      						<div class="article-image col-md-6 col-lg-4">
	      						<p>
	      						<%= image_tag article.image.url, class: "users-like-img" %>
	      						</p>
	      						<%= link_to article.title, article_path(article) %>
	      						</div> 
	 						<% end %>
						<% end %>
					</div>
	 			</div>
 			</div>
   		</div>
   	</div>
</div>



    